# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `concurrent-ruby` gem.
# Please instead update this file by running `bin/tapioca gem concurrent-ruby`.


# {include:file:README.md}
# load native parts first
# load native parts first
#
# pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/constants.rb:1
module Concurrent
  extend ::Concurrent::Utility::EngineDetector
end

# @!visibility private
# @!visibility private
# @!visibility private
# @!visibility private
# @!visibility private
#
# pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:7
module Concurrent::Collection; end

# @!visibility private
#
# pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:10
Concurrent::Collection::MapImplementation = Concurrent::Collection::MriMapBackend

# @!visibility private
#
# pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:10
class Concurrent::Collection::MriMapBackend < ::Concurrent::Collection::NonConcurrentMapBackend
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:12
  def initialize(options = T.unsafe(nil), &default_proc); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:17
  def []=(key, value); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:61
  def clear; end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:33
  def compute(key); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:21
  def compute_if_absent(key); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:29
  def compute_if_present(key); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:53
  def delete(key); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:57
  def delete_pair(key, value); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:49
  def get_and_set(key, value); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:37
  def merge_pair(key, value); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:45
  def replace_if_exists(key, new_value); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:41
  def replace_pair(key, old_value, new_value); end
end

# @!visibility private
#
# pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:9
class Concurrent::Collection::NonConcurrentMapBackend
  # WARNING: all public methods of the class must operate on the @backend
  # directly without calling each other. This is important because of the
  # SynchronizedMapBackend which uses a non-reentrant mutex for performance
  # reasons.
  #
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:15
  def initialize(options = T.unsafe(nil), &default_proc); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:21
  def [](key); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:25
  def []=(key, value); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:94
  def clear; end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:59
  def compute(key); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:29
  def compute_if_absent(key); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:53
  def compute_if_present(key); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:81
  def delete(key); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:85
  def delete_pair(key, value); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:99
  def each_pair; end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:71
  def get_and_set(key, value); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:110
  def get_or_default(key, default_value); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:77
  def key?(key); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:63
  def merge_pair(key, value); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:46
  def replace_if_exists(key, new_value); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:37
  def replace_pair(key, old_value, new_value); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:106
  def size; end

  private

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:130
  def dupped_backend; end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:124
  def initialize_copy(other); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:134
  def pair?(key, expected_value); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:116
  def set_backend(default_proc); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:138
  def store_computed_value(key, new_value); end
end

# @!macro concurrent_hash
#
# pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/hash.rb:49
class Concurrent::Hash < ::Hash; end

# @!macro internal_implementation_note
#
# pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/hash.rb:16
Concurrent::HashImplementation = Hash

# `Concurrent::Map` is a hash-like object and should have much better performance
# characteristics, especially under high concurrency, than `Concurrent::Hash`.
# However, `Concurrent::Map `is not strictly semantically equivalent to a ruby `Hash`
# -- for instance, it does not necessarily retain ordering by insertion time as `Hash`
# does. For most uses it should do fine though, and we recommend you consider
# `Concurrent::Map` instead of `Concurrent::Hash` for your concurrency-safe hash needs.
#
# pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:39
class Concurrent::Map < ::Concurrent::Collection::MriMapBackend
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:279
  def each; end

  # Iterates over each key.
  # @yield for each key in the map
  # @yieldparam key [Object]
  # @return [self]
  # @!macro map.atomic_method_with_block
  #
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:255
  def each_key; end

  # Iterates over each key value pair.
  # @yield for each key value pair in the map
  # @yieldparam key [Object]
  # @yieldparam value [Object]
  # @return [self]
  # @!macro map.atomic_method_with_block
  #
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:274
  def each_pair; end

  # Iterates over each value.
  # @yield for each value in the map
  # @yieldparam value [Object]
  # @return [self]
  # @!macro map.atomic_method_with_block
  #
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:264
  def each_value; end

  # Is map empty?
  # @return [true, false]
  #
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:291
  def empty?; end

  # Get a value with key, or default_value when key is absent,
  # or fail when no default_value is given.
  # @param [Object] key
  # @param [Object] default_value
  # @yield default value for a key
  # @yieldparam key [Object]
  # @yieldreturn [Object] default value
  # @return [Object] the value or default value
  # @raise [KeyError] when key is missing and no default_value is provided
  # @!macro map_method_not_atomic
  #   @note The "fetch-then-act" methods of `Map` are not atomic. `Map` is intended
  #     to be use as a concurrency primitive with strong happens-before
  #     guarantees. It is not intended to be used as a high-level abstraction
  #     supporting complex operations. All read and write operations are
  #     thread safe, but no guarantees are made regarding race conditions
  #     between the fetch operation and yielding to the block. Additionally,
  #     this method does not support recursion. This is due to internal
  #     constraints that are very unlikely to change in the near future.
  #
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:183
  def fetch(key, default_value = T.unsafe(nil)); end

  # Fetch value with key, or store default value when key is absent,
  # or fail when no default_value is given. This is a two step operation,
  # therefore not atomic. The store can overwrite other concurrently
  # stored value.
  # @param [Object] key
  # @param [Object] default_value
  # @yield default value for a key
  # @yieldparam key [Object]
  # @yieldreturn [Object] default value
  # @return [Object] the value or default value
  #
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:205
  def fetch_or_store(key, default_value = T.unsafe(nil)); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:162
  def get(key); end

  # @!visibility private
  #
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:321
  def inspect; end

  # Find key of a value.
  # @param [Object] value
  # @return [Object, nil] key or nil when not found
  #
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:284
  def key(value); end

  # All keys
  # @return [::Array<Object>] keys
  #
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:236
  def keys; end

  # @!visibility private
  #
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:305
  def marshal_dump; end

  # @!visibility private
  #
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:313
  def marshal_load(hash); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:163
  def put(key, value); end

  # Insert value into map with key if key is absent in one atomic step.
  # @param [Object] key
  # @param [Object] value
  # @return [Object, nil] the previous value when key was present or nil when there was no key
  #
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:215
  def put_if_absent(key, value); end

  # Is the value stored in the map. Iterates over all values.
  # @param [Object] value
  # @return [true, false]
  #
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:227
  def value?(value); end

  # All values
  # @return [::Array<Object>] values
  #
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:244
  def values; end

  private

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:331
  def initialize_copy(other); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:336
  def populate_from(hash); end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:327
  def raise_fetch_no_key; end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/map.rb:341
  def validate_options_hash!(options); end
end

# Various classes within allows for +nil+ values to be stored,
# so a special +NULL+ token is required to indicate the "nil-ness".
# @!visibility private
#
# pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/constants.rb:6
Concurrent::NULL = T.let(T.unsafe(nil), Object)

# @!visibility private
# @!visibility private
# @!visibility private
# @!visibility private
# @!visibility private
# @!visibility private
#
# pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/thread_safe/util.rb:4
module Concurrent::ThreadSafe; end

# @!visibility private
# @!visibility private
# @!visibility private
# @!visibility private
# @!visibility private
# @!visibility private
#
# pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/thread_safe/util.rb:7
module Concurrent::ThreadSafe::Util; end

# TODO (pitr-ch 15-Oct-2016): migrate to Utility::ProcessorCounter
#
# pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/thread_safe/util.rb:13
Concurrent::ThreadSafe::Util::CPU_COUNT = T.let(T.unsafe(nil), Integer)

# TODO (pitr-ch 15-Oct-2016): migrate to Utility::NativeInteger
#
# pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/thread_safe/util.rb:10
Concurrent::ThreadSafe::Util::FIXNUM_BIT_SIZE = T.let(T.unsafe(nil), Integer)

# pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/thread_safe/util.rb:11
Concurrent::ThreadSafe::Util::MAX_INT = T.let(T.unsafe(nil), Integer)

# @!visibility private
# @!visibility private
# @!visibility private
# @!visibility private
#
# pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/utility/engine.rb:3
module Concurrent::Utility; end

# @!visibility private
#
# pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/utility/engine.rb:6
module Concurrent::Utility::EngineDetector
  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/utility/engine.rb:7
  def on_cruby?; end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/utility/engine.rb:11
  def on_jruby?; end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/utility/engine.rb:27
  def on_linux?; end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/utility/engine.rb:23
  def on_osx?; end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/utility/engine.rb:15
  def on_truffleruby?; end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/utility/engine.rb:19
  def on_windows?; end

  # pkg:gem/concurrent-ruby#lib/concurrent-ruby/concurrent/utility/engine.rb:31
  def ruby_version(version = T.unsafe(nil), comparison, major, minor, patch); end
end
