inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-faker
  - rubocop-performance
  - rubocop-sorbet

Layout:
  Enabled: false

Style:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  DisplayStyleGuide: true
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - "bin/*"
    - "vendor/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "Guardfile"
    - "config/environments/*.rb"
    - "lib/tasks/*.rake"
    - "m2m_keygen.gemspec"

Gemspec/RequiredRubyVersion:
  Enabled: false
